projetoservletjsp/src/br/com/senai/HelloWorldMB.java
package br.com.senai;

import javax.faces.bean.ManagedBean;

@ManagedBean
public class HelloWorldMB {

	public String getMensagemInicial(){
		return "Hello World MB";
	}
	
}

projetoservletjsp/src/br/com/senai/UsuarioBean.java
package br.com.senai;

import javax.faces.bean.ManagedBean;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

@ManagedBean

@Entity
@Table(name = "usuario")
public class UsuarioBean {
	
	@Id
	@GeneratedValue
	private int id;
	
	@Column(name = "name", length = 30, nullable = false)	
	private String nome;
	
	@Column(name = "senha", length = 10, nullable = false)
	private String senha;
	
	@Column(name = "email", length = 30, nullable = false)
	private String email;	
	
	
	
	public UsuarioBean() {
		super();
	}
	
	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public String getNome() {
		return nome;
	}
	public void setNome(String nome) {
		this.nome = nome;
	}
	public String getSenha() {
		return senha;
	}
	public void setSenha(String senha) {
		this.senha = senha;
	}
	public String getEmail() {
		return email;
	}
	public void setEmail(String email) {
		this.email = email;
	}
	
	public void nomeFoiDigitado(){
		System.out.println("\nUsuarioBean");
	}

}

projetoservletjsp/WebContent/formUsuario.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"> 

<h:head>
    <title>Testando</title>
</h:head> 
<h:body> 
    <h:outputText value="testando"/>
</h:body> 
</html>

projetoservletjsp/WebContent/formularioUsuarioAlterar.jsp
<?xml version="1.0" encoding="ISO-8859-1" ?>
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
	pageEncoding="ISO-8859-1"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />
<title>Cadastro de Usuario</title>
<link rel="stylesheet" type="text/css" href="css/bootstrap.css" />

<style>
.jumbotron {
	width: 500px;
	text-align: center;
	margin-left: auto;
	margin-right: auto;
	margin-top: 20px;
}

.table {
	width: 450px;
	margin-top: 20px;
	margin-left: auto;
	margin-right: auto;
}

.form-control {
	width: 350px;
	margin-bottom: 5px;
	margin-left: auto;
	margin-right: auto;
}

.btn-block {
	width: 350px;
	margin-left: auto;
	margin-right: auto;
}
</style>

</head>
<body>
	<div class="jumbotron">
		<form action="formularioUsuario?acao=alterar" method="post">

			<table class="table">
				<tr>
					<td>
						<input type="hidden" name="id" value="${usuario.id}"/>
					</td>
				</tr>
				<tr>
					<td><input class="form-control" type="text" name="nome"
						placeholder="Nome" value="${usuario.nome}" /></td>
				</tr>
				<tr>
					<td><input class="form-control" type="password" name="senha"
						placeholder="Senha" value="${usuario.senha}"/></td>
				</tr>
				<tr>
					<td><input class="form-control" type="text" name="email"
						placeholder="Email" value="${usuario.email}"/></td>
				</tr>	
				 			
				<tr>
					<td colspan="2"><input type="submit" value="alterar"
						class="btn btn-primary btn-block" /></td>
				</tr>
			</table>
			
			
		      
			<%-- <h4>Telefones</h4>
			
			<div id="Lista_telefone" class="container">
			<c:forEach var="telefone" items="${telefones}">
			 <input class="form-control" type="text" id="${telefone.id}"
			 name="telefone[]">${telefone.numero}</input>
			</c:forEach>			
			</div> --%>
			

		</form>
	</div>
</body>
</html>

projetoservletjsp/WebContent/formularioUsuarioBean.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui">

<h:head></h:head>
<h:body>
	<h:form>
    <p:panel id="panel" header="Cadastro de Usuario">

		<p:focus context="panel" />

		<p:messages />

		<h:panelGrid columns="15">
			<p:outputLabel for="nome" value="Nome" />
			<p:inputText id="nome" value="#{usuarioBean.nome}"
				required="true" label="Sobrenome">
				<f:validateLength minimum="2" />
				
			</p:inputText>
			
			<p:message for="nome" />

			<p:outputLabel for="senha" value="Senha" />
			<p:inputText id="senha" value="#{usuarioBean.senha}" required="true"
				label="Senha" />
			<p:message for="senha" />
			
			<p:outputLabel for="email" value="Email" />
            <p:inputText id="email" value="#{usuarioBean.email}" required="true"
                label="Email" />
            <p:message for="email" />
		</h:panelGrid>

		<p:commandButton id="submitButton" value="Salvar" update="@parent"
			actionListener="#{focusView.save}" />
	</p:panel>
	</h:form>
</h:body>
</html>

projetoservletjsp/WebContent/index.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui">

<h:head>

	<title>Hello World JSF</title>

</h:head>

<h:body>

	<h:outputText value="#{helloWorldMB.mensagemInicial}" />

	<h:form>

		<h:panelGrid>

			<p:inputText value="#{helloWorldMB.nome}" />

			<p:commandButton ajax="false" action="#{helloWorldMB.acao()}"
				value="Submeter" />

			<h:outputText value="#{helloWorldMB.nome}" />

			<p:inputTextarea autoResize="false" value="#{helloWorldMB.textArea}" />

			<h:selectOneMenu value="#{helloWorldMB.select}">

				<f:selectItem itemLabel="Opção 1" itemValue="1" />

				<f:selectItem itemLabel="Opção 2" itemValue="2" />

			</h:selectOneMenu>

			<p:pickList itemLabel="#{usuario}"
				value="#{helloWorldMB.dualListUsuario}" var="usuario">

			</p:pickList>

			<p:dataTable value="#{helloWorldMB.listaUsuario}" var="usuario">
				<p:column>

					<h:outputText value="#{usuario.nome}" />

				</p:column>

			</p:dataTable>

		</h:panelGrid>

	</h:form>

</h:body>

</html>

projetoservletjsp/WebContent/listarUsuario.jsp
<?xml version="1.0" encoding="ISO-8859-1" ?>
<%@page import="br.com.senai.Usuario"%>
<%@page import="java.util.List"%>
<%@page import="br.com.senai.UsuarioDAO"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
	pageEncoding="ISO-8859-1"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />
<link rel="stylesheet" type="text/css" href="css/bootstrap.css" />
<title>Listar Usuario</title>
<style>
.jumbotron {
	width: 500px;
	text-align: center;
	margin-left: auto;
	margin-right: auto;
	margin-top: 20px;
}

.table {
	width: 450px;
	margin-top: 20px;
	margin-left: auto;
	margin-right: auto;
}

.form-control {
	width: 350px;
	margin-bottom: 5px;
	margin-left: auto;
	margin-right: auto;
}

.btn-block {
	width: 350px;
	margin-left: auto;
	margin-right: auto;
}
</style>
</head>
<body>
	<div class="jumbotron">
		<h4><a href="index.html">Home</a></h4>
		<h4><a href="formularioUsuario.jsp">Cadastrar usuario</a></h4>
		<%
			UsuarioDAO dao = new UsuarioDAO();
			List<Usuario> listaUsuario = dao.listarUsuario();
		%>
		<table class="table">
			<tr>
				<th>Nome</th>
				<th>Email</th>
				<th>Senha</th>
				<th></th>
			</tr>
			<%
				for (Usuario usuario : listaUsuario) {
			%>
			<tr>
				<td><%=usuario.getNome()%></td>
				<td><%=usuario.getEmail()%></td>
				<td><%=usuario.getSenha()%></td>			
				<td><a
					href="formularioUsuario?acao=prealterar&id=<%=usuario.getId()%>">Alterar</a></td>
				<td><a
					href="formularioUsuario?acao=excluir&id=<%=usuario.getId()%>">Excluir</a></td>
			</tr>
			<%
				}
			%>
		</table>
	</div>

</body>
</html>