projetospring/src/main/java/br/com/senai/model/Professor.java
package br.com.senai.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.ManyToOne;
import javax.persistence.Table;;

@Entity
@Table(name = "professor")
public class Professor extends Pessoa{

	
	@Column(name = "instituicao", length = 50, nullable = false)
	private String instituicaoEnsino;
	
	@Column(name = "dtAdmissao", length = 30, nullable = false)
	private String dtAdmissao;
	/*@Temporal(TemporalType.DATE)
	private Date dtAdmissao;*/	
	
	@ManyToOne	
	private Titulacao titulacao;
	

	public String getInstituicaoEnsino() {
		return instituicaoEnsino;
	}

	public void setInstituicaoEnsino(String instituicaoEnsino) {
		this.instituicaoEnsino = instituicaoEnsino;
	}

	public String getDtAdmissao() {
		return dtAdmissao;
	}

	public void setDtAdmissao(String dtAdmissao) {
		this.dtAdmissao = dtAdmissao;
	}
	
	
	
	public Titulacao getTitulacao() {
		return titulacao;
	}

	/*public Date getDtAdmissao() {
		return dtAdmissao;
	}

	public void setDtAdmissao(Date dtAdmissao) {
		this.dtAdmissao = dtAdmissao;
	}
*/
	public void setTitulacao(Titulacao titulacao) {
		this.titulacao = titulacao;
	}
	
}

projetospring/src/main/java/br/com/senai/view/AlunoEditMB.java
package br.com.senai.view;

import java.util.List;
import java.util.Random;

import javax.annotation.PostConstruct;
import javax.inject.Named;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.web.context.WebApplicationContext;

import br.com.senai.model.Aluno;
import br.com.senai.model.Endereco;
import br.com.senai.model.Professor;
import br.com.senai.model.Sexo;
import br.com.senai.model.Telefone;
import br.com.senai.model.TipoPessoa;
import br.com.senai.support.Fachada;

@Scope(value = WebApplicationContext.SCOPE_REQUEST)
@Named(value = "alunoEditMB")
public class AlunoEditMB {

	@Autowired	
	private Fachada fachada;
	
	private Aluno aluno;
	private Sexo sexo;
	private TipoPessoa tipoPessoa;	
	
	
	public List<Endereco> getListaEndereco(){
		return fachada.listarEndereco();
	}
	
	public List<Telefone> getListaTelefone(){
		return fachada.listarTelefone();
	}
	
	@PostConstruct
	private void init() {		
		aluno = new Aluno();		
	}

	public void preAlterar(Aluno aluno) {
		setAluno(aluno);
		
	}

	public String salvar() {
		//gerar a matricula randomicamente(Automaticamente)
		int matricula = Math.abs(new Random().nextInt());
		aluno.setMatricula(matricula);
		fachada.salvarAluno(aluno);		
		return "success";
	}

	public Aluno getAluno() {
		return aluno;
	}

	public void setAluno(Aluno aluno) {
		this.aluno = aluno;
	}

	public Sexo[] getSexo() {
		return sexo.values();
	}

	public void setSexo(Sexo sexo) {
		this.sexo = sexo;
	}

	public TipoPessoa[] getTipoPessoa() {
		return tipoPessoa.values();
	}

	public void setTipoPessoa(TipoPessoa tipoPessoa) {
		this.tipoPessoa = tipoPessoa;
	}
	
}

projetospring/WebContent/pages/private/professor/professorEdit.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui">

<h:head></h:head>
<h:body>

	<ui:composition template="/pages/private/index.xhtml">
		<ui:define name="conteudo">
			<p:panelGrid columns="1" styleClass="width600px">
				<h:inputHidden value="#{professorEditMB.professor.id}" />

				<p:inputText placeholder="Nome" required="true" label="Nome"
					value="#{professorEditMB.professor.nome}" styleClass="width500px"
					maxlength="30" />

				<p:inputMask mask="999999999-99" placeholder="CPF" required="true"
					label="CPF" value="#{professorEditMB.professor.cpf}"
					styleClass="width500px" maxlength="30" />

				<p:selectOneMenu value="#{professorEditMB.professor.sexo}"
					style="width:225px">
					<f:selectItem itemLabel="Sexo" itemValue="" />
					<f:selectItems itemLabel="#{sexo.descricao}" itemValue="#{sexo}"
						var="sexo" value="#{professorEditMB.sexo}" />
				</p:selectOneMenu>

				<p:selectOneMenu value="#{professorEditMB.professor.tipoPessoa}"
					style="width:225px">
					<f:selectItem itemLabel="Tipo de Pessoa" itemValue="" />
					<f:selectItems itemLabel="#{tipoPessoa.descricao}"
						itemValue="#{tipoPessoa}" var="tipoPessoa"
						value="#{professorEditMB.tipoPessoa}" />
				</p:selectOneMenu>

				<p:inputText placeholder="Instituicao" required="true"
					label="Instituicao"
					value="#{professorEditMB.professor.instituicaoEnsino}"
					styleClass="width500px" maxlength="30" />

				 <p:inputText placeholder="Data de Admissao" required="true"
					label="Data de Admissao"
					value="#{professorEditMB.professor.dtAdmissao}"
					styleClass="width500px" maxlength="30" />
					
				<!-- <p:inputText placeholder="Data de Admissao" required="true"
                    label="Data de Admissao"
                    value="#{professorEditMB.professor.dtAdmissao}"
                    styleClass="width500px" maxlength="30" >	
				    <f:convertDateTime  pattern = "dd.MM.yyyy"  timeZone = "EST"  type = "dtAdmissao"  /> 	
                </p:inputText>  -->
                   
				<p:selectOneMenu value="#{professorEditMB.professor.titulacao}"
					style="width:225px">
					<f:selectItem itemLabel="Titulação" itemValue="" />
					<f:selectItems itemLabel="#{titulacao.titulo}"
						itemValue="#{titulacao}" var="titulacao"
						value="#{professorEditMB.listaTitulacao}" />
				</p:selectOneMenu>

				<p:selectOneMenu value="#{professorEditMB.professor.endereco}"
					style="width:225px">
					<f:selectItem itemLabel="Logradouro" itemValue="" />
					<f:selectItems itemLabel="#{endereco.logradouro}"
						itemValue="#{endereco}" var="endereco"
						value="#{professorEditMB.listaEndereco}" />
				</p:selectOneMenu>

				<p:selectOneMenu value="#{professorEditMB.professor.endereco}"
					style="width:225px">
					<f:selectItem itemLabel="Bairro" itemValue="" />
					<f:selectItems itemLabel="#{endereco.bairro}"
						itemValue="#{endereco}" var="endereco"
						value="#{professorEditMB.listaEndereco}" />
				</p:selectOneMenu>

				<p:selectOneMenu value="#{professorEditMB.professor.telefone}"
					style="width:225px">
					<f:selectItem itemLabel="Numero de Telefone" itemValue="" />
					<f:selectItems itemLabel="#{telefone.numero}" itemValue="#{telefone}"
						var="telefone" value="#{telefoneListMB.listaTelefone}" />
				</p:selectOneMenu>

				<p:commandButton value="salvar" action="#{professorEditMB.salvar()}"
					ajax="false" />
			</p:panelGrid>
		</ui:define>
	</ui:composition>

</h:body>
</html>

projetospring/WebContent/pages/private/professor/professorList.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:p="http://primefaces.org/ui">

<h:head></h:head>
<h:body>

    <ui:composition template="/pages/private/index.xhtml">
        <ui:define name="conteudo">
            <p:dataTable id="datatable" var="professor"
                value="#{professorListMB.listaProfessor}" paginator="true" rows="10">
                
                <p:column headerText="Nome" sortBy="#{professor.nome}">
                    <h:outputText value="#{professor.nome}" />
                </p:column>
                
                <p:column headerText="CPF" sortBy="#{professor.cpf}">
                    <h:outputText value="#{professor.cpf}" />
                </p:column>
                             
                <p:column headerText="Sexo" sortBy="#{professor.sexo}">
                    <h:outputText value="#{professor.sexo.descricao}" />
                </p:column>
                                
                <p:column headerText="Tipo de Professor" sortBy="#{professor.tipoPessoa}">
                    <h:outputText value="#{professor.tipoPessoa.descricao}" />
                </p:column>
                
                <p:column headerText="Instituíção de Ensino" sortBy="#{professor.instituicaoEnsino}">
                    <h:outputText value="#{professor.instituicaoEnsino}" />
                </p:column>
                
                <p:column headerText="Data de Admissao" sortBy="#{professor.dtAdmissao}">
                    <h:outputText value="#{professor.dtAdmissao}" />
                </p:column>
                
                <p:column headerText="Titulação" sortBy="#{professor.titulacao}">
                    <h:outputText value="#{professor.titulacao.titulo}" />
                </p:column>
                
               <p:column headerText="Logradouro" sortBy="#{professor.endereco}">
                    <h:outputText value="#{professor.endereco.logradouro}" />
                </p:column>
                
                <p:column headerText="Bairro" sortBy="#{professor.bairro}">
                    <h:outputText value="#{professor.endereco.bairro}" />
                </p:column>
                                
                <p:column headerText="DDD" sortBy="#{professor.telefone}">
                    <h:outputText value="#{professor.telefone.ddd}" />
                </p:column>
                             
                <p:column>
                    <p:commandLink
                        actionListener="#{professorEditMB.preAlterar(professor)}"
                        action="professorEdit.xhtml">alterar</p:commandLink>
                </p:column>
                <p:column>
                    <p:commandLink update="datatable"
                        actionListener="#{professorListMB.excluir(professor)}">excluir</p:commandLink>
                </p:column>
            </p:dataTable>
        </ui:define>
    </ui:composition>

</h:body>
</html>